import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/footer";
import SmoothScroll from "@/components/gsap/SmoothScroll";
import ClickSpark from "@/components/ui/ClickSpark";
import { CartProvider } from "@/components/ui/cart/CartContext";
import {ToastContainer} from "react-toastify"
import { Providers } from "./providers";
import FloatingAIChat from "@/components/FloatingAI";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BreadVerse - Artisanal Bakery",
  description: "Generated by yours truly, Bababoi the chosen one",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` }
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
           {/* Wrap with CartProvider */}
            <ToastContainer 
              position="top-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="dark"
            />
          <ClickSpark sparkSize={10} sparkRadius={15} sparkCount={8} duration={400}>
            <Providers>
              <CartProvider>
          <Navbar/>
          <SmoothScroll>
            <FloatingAIChat/>
          {children}
       
            <Footer/>
          </SmoothScroll>
          </CartProvider>
           </Providers>
          </ClickSpark>
          
        </ThemeProvider>
        
      </body>
    </html>
  );
}
